export { default as Home } from './Auth/Home';
export { default as Admin } from './Auth/Admin';
export { default as About } from './Auth/About';
export { default as Login } from './Auth/Login';
export { default as Landing} from './Auth/Landing';
export { default as Feedback } from './Auth/Feedback';
export { default as UserEdit } from './Auth/UserEdit';
export { default as Register } from './Auth/Register';
export { default as AddMoment } from './Auth/AddMoment';
export { default as ResetPass } from './Auth/ResetPass';
export { default as Dashboard } from './Auth/Dashboard';
export { default as EditMoment } from './Auth/EditMoment';
export { default as SearchUser } from './Auth/SearchUser';
export { default as SingleImage } from './Auth/SingleImage';
export { default as EmailVarify } from './Auth/EmailVarify';
export { default as PageNotFound } from './Auth/PageNotFound';